### ISSUE TITLE
Support making rules for the UDP protocol

### ISSUE THREAD

**Issue by pvandervelde** [lynx44/windows_firewall#10]

**Comment by congaframe** [comment]
Hi,
I tried to create rules for UDP but it failed with error message:
Option protocol must be equal to one of : TCP! you passed UDP
Could you please confirm that this cookbook support UDP ?

thanks

**Comment by lynx44** [comment]
This has been updated thanks to [this pull request](https://github.com/lynx44/windows_firewall/pull/14). It's been published to the Chef Supermarket under version 3.0.0.
