### ISSUE TITLE
ChefSpec Matcher

### ISSUE THREAD

**Issue by bpholt** [lynx44/windows_firewall#18]
Have you considered adding a ChefSpec matcher for the `windows_firewall_rule` resource? We wrote one we’re using in our tests, so I can send a PR pretty easily if you’re open to it. I also saw http://blog.standardedge.com/2014/01/chefspec-automatically-resolve-resource.html, so I figured it was worth asking first in case you would rather just encourage people to use automatic matchers.

**Comment by lynx44** [comment]
I'm certainly not against it, feel free to send the PR! I know I'm way out of the norm with automatic resource matchers.

**Comment by Z3r0Sum** [comment]
@lynx44 I saw this issue afterwards, but I just opened PR #20 to address this issue.

**Comment by bpholt** [comment]
Thanks @Z3r0Sum—I didn't get a chance to submit the PR immediately and then forgot about it. Glad it's moving forward.

**Comment by lynx44** [comment]
Resolved in https://github.com/lynx44/windows_firewall/pull/20
