### ISSUE TITLE
License for cookbook?

### ISSUE THREAD

**Issue by mattstratton** [lynx44/windows_firewall#3]
I'm doing a bit of work on a fork of this cookbook, and it is set to All Rights Reserved. What license should it be set to?

**Comment by lynx44** [comment]
Good point - Apache seems good to me, looks like most other opscode cookbooks are using the same. By the way, have you seen the pull request by @chlsmith? I haven't had a chance to review it yet, but I'm not sure if it has work in it that intersects with what you're doing.

**Comment by mattstratton** [comment]
Ha. It actually does. There is some duplication, but I'm doing a lot of other cleanup too. I'm also adding some (albeit not completely supported) test-kitchen support, so it's going to be a decent sized PR when I'm done (hopefully in a few hours). I wonder if you should create another branch in here and merge the @chlsmith PR into there, and I can pull his stuff into mine?

**Comment by lynx44** [comment]
Sure -- just pulled it into branch chlsmith-20150205

**Comment by mattstratton** [comment]
Addressed in PR #4
