### ISSUE TITLE
2.0.0 Release

### ISSUE THREAD

**Issue by lynx44** [lynx44/windows_firewall#7]
Starting a new issue for discussion. Just created a new branch for 2.0.0. I made just a couple of small changes.

One is a breaking change as @mattstratton suggested - change :open action to :create.

There was also a minor bug when the program parameter was left empty, since the if block would detect a non-empty string due to double quotes, and it would end up putting the wireless settings in the Program field. I added a check just to make sure that the value is either null, an empty string or empty double quotes (""), and if so, ignore it.

@mattstratton and @chlsmith - I'd appreciate it if you could give the 2.0.0 branch a once over. If everything looks good, I'll merge it into the master branch.

**Comment by mattstratton** [comment]
I'll check it out later tonight. I like action "create" as I would like to introduce a "delete" or "remove" action eventually too. @johnsmyth and I were discussing this. 

We also need to eventually discuss the manner in which the attribute parameters can be made idempotent, but that's a conversation for another day. I have an issue open on my own fork with this and I'll transfer it over here.

**Comment by mattstratton** [comment]
I just added a small PR #8 which I would suggest merge in before the release, although it doesn't affect the cookbook itself at all, and they are files that would not be published to Supermarket, so with or without the PR I say

:+1:

**Comment by mattstratton** [comment]
Everything has been tested on my end. I suggest merging to master and publishing 2.0 to Supermarket.
